language: python

python:
  - 3.6

cache: pip

install:
  - pip install --upgrade pip
  - pip install --progress-bar off -e .[develop]
  - pip install sphinx
  - pip install sphinx_rtd_theme

script:
  - cd docs
  - make html && mv ./build/html ./build/docs && rm -r ./build/doctrees
  - cd ..
  - gem install travis --no-document

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $DEPLOY_KEY
    keep-history: true
    repo: thu-coai/ConvLab-2_docs
    target-branch: master
    local-dir: ./docs/build
    on:
      branch: master
  # - provider: script
    # skip-cleanup: true
    # script: coveralls
    # on:
      # all_branches: true
      # condition: true
